
# Controls when the workflow will run
on:
  create:
    branches: 
      - release/**

name: Create Release

jobs:
  build:
    
    env:
      BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION
    - name: Test
      run: |
        dotnet test ./HttpHmacAuthentication.sln
    - name: Pack
      run: dotnet pack --no-build --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION -p:PackageVersion=$BUILD_VERSION
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/release')
      run: dotnet nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
